edit and delete category
VnVSchool/blog pull request #6
Opened 2023-04-26 15:42 UTC by victoriadv

2023-04-26 15:49 UTC, volodymyr2000mandzyniak approved these changes

2023-04-28 19:37 UTC, volodymyr2000mandzyniak approved these changes

2023-04-29 13:05 UTC, Luzhnuy commented
Please merge your two branches and open one pull request

2023-04-29 13:09 UTC, Luzhnuy requested changes

2023-04-29 13:09 UTC, Luzhnuy commented on models/articles/models.py
> +    __tablename__ = 'article'
Please rename tables to be plural name.
For example:
article -> articles
category - > categories

2023-04-29 13:09 UTC, Luzhnuy commented on routes/articles/routes.py
> +@app.route("/category/<int:id>/delete")
Add blank lines before other route

2023-05-05 17:52 UTC, volodymyr2000mandzyniak approved these changes

2023-05-05 17:52 UTC, volodymyr2000mandzyniak approved these changes

2023-05-05 17:54 UTC, volodymyr2000mandzyniak approved these changes

2023-05-05 17:54 UTC, volodymyr2000mandzyniak approved these changes

2023-05-06 12:59 UTC, Luzhnuy commented
Please resolve the comments and conflicts

2023-05-06 13:00 UTC, Luzhnuy commented
Remove second pull request

2023-05-10 18:36 UTC, Luzhnuy approved these changes

2023-05-17 16:07 UTC, Luzhnuy approved these changes

2023-05-17 18:33 UTC, merged